config/routes.rb
SomeApp::Application.routes.draw do
  resources :an_entities

end

app/models/an_entity.rb
class AnEntity < ActiveRecord::Base
  attr_accessible :attr1, :attr2
end

app/controllers/an_entities_controller.rb
class AnEntitiesController < ApplicationController
  # GET /an_entities
  # GET /an_entities.json
  def index
    @an_entities = AnEntity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @an_entities }
    end
  end

  # GET /an_entities/1
  # GET /an_entities/1.json
  def show
    @an_entity = AnEntity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @an_entity }
    end
  end

  # GET /an_entities/new
  # GET /an_entities/new.json
  def new
    @an_entity = AnEntity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @an_entity }
    end
  end

  # GET /an_entities/1/edit
  def edit
    @an_entity = AnEntity.find(params[:id])
  end

  # POST /an_entities
  # POST /an_entities.json
  def create
    @an_entity = AnEntity.new(params[:an_entity])

    respond_to do |format|
      if @an_entity.save
        format.html { redirect_to @an_entity, notice: 'An entity was successfully created.' }
        format.json { render json: @an_entity, status: :created, location: @an_entity }
      else
        format.html { render action: "new" }
        format.json { render json: @an_entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /an_entities/1
  # PUT /an_entities/1.json
  def update
    @an_entity = AnEntity.find(params[:id])

    respond_to do |format|
      if @an_entity.update_attributes(params[:an_entity])
        format.html { redirect_to @an_entity, notice: 'An entity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @an_entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /an_entities/1
  # DELETE /an_entities/1.json
  def destroy
    @an_entity = AnEntity.find(params[:id])
    @an_entity.destroy

    respond_to do |format|
      format.html { redirect_to an_entities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/an_entities_helper.rb
module AnEntitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/an_entities/_form.html.erb
<%= form_for(@an_entity) do |f| %>
  <% if @an_entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@an_entity.errors.count, "error") %> prohibited this an_entity from being saved:</h2>

      <ul>
      <% @an_entity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attr1 %><br />
    <%= f.text_field :attr1 %>
  </div>
  <div class="field">
    <%= f.label :attr2 %><br />
    <%= f.text_field :attr2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/an_entities/edit.html.erb
<h1>Editing an_entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @an_entity %> |
<%= link_to 'Back', an_entities_path %>

app/views/an_entities/index.html.erb
<h1>Listing an_entities</h1>

<table>
  <tr>
    <th>Attr1</th>
    <th>Attr2</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @an_entities.each do |an_entity| %>
  <tr>
    <td><%= an_entity.attr1 %></td>
    <td><%= an_entity.attr2 %></td>
    <td><%= link_to 'Show', an_entity %></td>
    <td><%= link_to 'Edit', edit_an_entity_path(an_entity) %></td>
    <td><%= link_to 'Destroy', an_entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New An entity', new_an_entity_path %>

app/views/an_entities/new.html.erb
<h1>New an_entity</h1>

<%= render 'form' %>

<%= link_to 'Back', an_entities_path %>

app/views/an_entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Attr1:</b>
  <%= @an_entity.attr1 %>
</p>

<p>
  <b>Attr2:</b>
  <%= @an_entity.attr2 %>
</p>


<%= link_to 'Edit', edit_an_entity_path(@an_entity) %> |
<%= link_to 'Back', an_entities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SomeApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>